app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from .import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__='users'

    id=db.Column(db.Integer,primary_key=True)
    username=db.Column(db.String(250),index=True)
    email=db.Column(db.String(250),unique=True,index=True)
    pass_secure=db.Column(db.String(250))
    profile=db.Column(db.String(250))
    about=db.Column(db.String(250))
    occupation=db.Column(db.String(250))

    @property
    def password(self):
        raise AttributeError("You can not read this")

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f"User {self.username}"

class Blogs(db.Model):
    __tablename__='blogs'
    id=db.Column(db.Integer,primary_key=True)
    title=db.Column(db.String())
    body=db.Column(db.String())



class Comments(db.Model):
    __tablename__='comments'
    id=db.Column(db.Integer,primary_key=True)
    email=db.Column(db.String())
    username=db.Column(db.String())
    comment=db.Column(db.String())
    blog_id=db.Column(db.Integer)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    

    def save_comments(self):
        db.session.add(self);
        db.session.commit()

    @classmethod
    def get_comments(cls,id):
        comments=Comments.query.filter_by(blog_id=id).all()
        return comments

class Quote:
    def __init__(self,quote,author):
        self.quote=quote
        self.author=author




class Role(db.Model):
    __tablename__='roles'
    id=db.Column(db.Integer,primary_key=True)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,ValidationError,BooleanField,TextAreaField
from wtforms.validators import Required,Email,EqualTo

class CommentForm(FlaskForm):
    email=StringField('Your email ',validators=[Required(),Email()])
    name=StringField("Your name",validators=[Required()])
    comment=TextAreaField("Comment",validators=[Required()])
    submit=SubmitField("Submit")

class AdminBlog(FlaskForm):

    title=StringField("Title",validators=[Required()])
    body=TextAreaField("Blog Body")
    submit=SubmitField("Submit")

class DeleteBlog(FlaskForm):
    delete=SubmitField("Delete this Blog")

class DeleteComment(FlaskForm):
    delete1=SubmitField("Delete")

class UpdateProfile(FlaskForm):
    about=TextAreaField("Tell us about you ",validators=[Required()])
    occupation=StringField("What is you current occupation",validators=[Required()])
    submit=SubmitField("Save")

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_mail import Message
from flask_uploads import UploadSet,configure_uploads,IMAGES

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
photos = UploadSet('photos',IMAGES)

def create_app(config_name):
    app = Flask(__name__)
    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    configure_uploads(app,photos)
    mail = Mail(app)
    
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from . import main
from flask import render_template,redirect,url_for,flash,request,abort
from .forms import CommentForm,AdminBlog,DeleteBlog,DeleteComment,UpdateProfile
from .. import db,photos
# import markdown2
from ..models import Blogs,Comments,User
from ..request import get_quote
# from ..email import mail_message



@main.route("/",methods=['POST','GET'])
def index():
    quote=get_quote()
    title="Blog"
    message="Mental Health Wellness"
    blogs=Blogs.query.all()
    top_blog=Blogs.query.all()
    top_blog.reverse()
    topBlog=top_blog[0:1]
    commento=Comments.query.filter_by(blog_id=500).all()
    form = CommentForm()
    if form.validate_on_submit():
        comments=Comments(blog_id=500,email=form.email.data,username=form.name.data,comment=form.comment.data)
        comments.save_comments()
        return redirect(url_for('main.index'))
    return render_template("index.html",commento=commento,topBlog=topBlog,quote=quote,message=message,title=title,comments=form,blogs=blogs)

@main.route("/new_blog",methods=["POST","GET"])
def new_blog():
    #query all emails
    emails=Comments.query.all()
    all_emails=[]
    for emal in emails:
        all_emails.append(emal.email)


    form=AdminBlog()
    if form.validate_on_submit():
        blog=Blogs(title=form.title.data,body=form.body.data)
        db.session.add(blog)
        db.session.commit()
        mail_message("Hello A new Blog has been posted","email/welcome_user","")
        return redirect(url_for('main.index'))

    title="Write a blog"
    return render_template("new_blog.html",title=title,newBlog=form,all_emails=all_emails)

@main.route("/read_blog/title/<int:id>/",methods=['GET','POST'])
def read_blog(id):
    blog_id=id
    title="Blog"
    message="Welcome to my Blog"
    blog=Blogs.query.filter_by(id=id).first()
    blogs=Blogs.query.all()
    data=blog.title
    form = CommentForm()

    if form.validate_on_submit():
        comments=Comments(blog_id=id,email=form.email.data,username=form.name.data,comment=form.comment.data)
        comments.save_comments()
        return redirect(url_for('main.read_blog',id=blog_id))



    format_blog=markdown2.markdown(blog.body,extras=["code-friendly", "fenced-code-blocks"])

    blog_comment=Comments.query.filter_by(blog_id=id).all()


    del_form=DeleteBlog()
    dele=Blogs.query.filter_by(id=id).first()
    if del_form.validate_on_submit():

        db.session.delete(dele)
        db.session.commit()
        
        return redirect(url_for('main.index'))



    del_comment=DeleteComment()

    if del_comment.validate_on_submit():
        dele_com=Comments.query.filter_by(blog_id=id).first()
        db.session.delete(dele_com)
        db.session.commit()

        return redirect(url_for('main.read_blog',id=blog_id))



    return render_template("read_blog.html",deleteform=del_form,data=data,blogComment=blog_comment,format_blog=format_blog,message=message,title=title,comments=form,blogs=blogs,id=id,del_comment=del_comment)

#profile picture

@main.route("/profile/<uname>")
def profile(uname):
    user=Users.query.filter_by(username=uname).first()
    if user is None:
        abort(404)

    return render_template("profile/profile.html",user=user)

@main.route("/profile/<uname>/update",methods=['GET','POST'])
def update_profile(uname):
    user=Users.query.filter_by(username=uname).first()
    if user is None:
        abort(404)
    form =UpdateProfile()
    if form.validate_on_submit():
        user.about=form.about.data
        user.occupation=form.occupation.data
        db.session.add(user)
        db.session.commit()

        return redirect(url_for(".profile",uname=user.username))

    return render_template("profile/update.html",form=form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
def update_pic(uname):
    user = Users.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile= path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%} -->

 Navbar block  
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %} 

app/templates/index.html
{%extends 'base.html'%}
{%import "bootstrap/wtf.html" as wtf%}
{%block content%}
<div id="welcome" class="jumbotron">
  <h1>{{message}}</h1>
  <p>Our community talks about mental health with compassion and without judgment.</p>
  {%for quo in quote%}
    <p>{{quo.quote}}</p>
    <i>~~{{quo.author}}~~</i>
  {%endfor%}
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <div class="container">
        <h1 id="h1" style="text-align:center">Let's talk about Mental Health!</h1>
        <img id="health" src="../static/whatisblog.png" alt="Mental health question">
        <h3>What do you really mean when you say “I’m fine”?</h3>
        <p>I’m not currently in therapy, but I think if I was, a therapist would help me work through my dangerous habit of over-saying “I’m fine.” Sure, it’s an OK response in the checkout line of a grocery store. It’s also valid in large settings or groups where we don’t feel comfortable letting our walls down. But I tend slather it all over one-on-one conversations with people I care about, as well as during doctor’s appointments where I’m the direct opposite of decent.</p>
        <h4>When I say "I'm fine", I tend to mean:</h4>
        <ul>
          <li>I'm not doing well.</li>
          <li>I'm numb.</li>
          <li>My life is not what I want it to be but I'm still here.</li>
        </ul>
        <p>What about you? If you’re comfortable, feel free to use the comments section of this post to say how you truly are and let it be a small step in the right direction of healing.</p>


        <br>
        <hr class="bg-info">
        <h1>Comments....</h1>
        <div class="container">
          <div class="comments">
            {%for comment in commento%}
            <div class="comments card">
              <div class="card-header">

                <p>{{comment.username}} commented on {{comment.posted}}</p>
              </div>
              <div class="card-body">
                  <p>{{comment.comment}}</p>
              </div>
              <div class="card-footer">

                {%if current_user.is_authenticated%}
                <a href="" data-method="delete" data-confirm="Are you sure?">admin online</a>
                {%endif%}
              </div>
            </div>

            {%endfor%}

          </div>
          <div class="row">

            <div class="col-md-2">

            </div>
            <div class="col-md-8">
              <div class="">
                <h3>Add a comment</h3>
                <i class="alert alert-info"><b>By commenting you've automatically subscribed</b></i>
                <br>
                {{wtf.quick_form(comments)}}

              </div>
            </div>
            <div class="col-md-2">
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

{%endblock%}



  

  
  
  

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> <STrong>BLOG-APP</STrong></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/"><strong>HOME</strong></a></li>
            </ul>    
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li style="color:white;padding:15px;">{{current_user.username}}</li>
            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}"><STrong>SIGN IN</STrong></a></li>
            {%endif%}
          </ul>

    </div>
</div> 

app/templates/new_blog.html
{%extends 'base.html'%}
{%import 'bootstrap/wtf.html' as wtf%}
{%block content%}

<div class="container">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      {{wtf.quick_form(newBlog)}}
      {{simplemde.load}}
    </div>
     <div class="col-md-3"> 
    </div>
  </div>
</div>
{%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>
    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>
  {% if user == current_user %}
  <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
  <!--Display profile photo-->
  <div class="col-md-4">
    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
  <div class="col-md-4">
    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
 .........
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}